services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    restart: unless-stopped

volumes:
  node-red-data:
