services:
  app:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped

volumes:
  portainer-data:
    driver: local
